# based off of
# https://github.com/vfarcic/docker-flow-cron/blob/1988f134fcc863b0832561121c1428f76f35db83/.travis.yml
env:
  DOCKER_COMPOSE_VERSION: 1.12.0
  TAG: 0.${TRAVIS_BUILD_NUMBER}

services:
  - docker
before_install:
  # need docker 1.13.0+ for compose file 3.0 which is required for pushing stacks
  # https://gist.github.com/dylanscott/ea6cff4900c50f4e85a58c01477e9473
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -cs) main" > /etc/apt/sources.list.d/docker.list'
  - curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get -y install "docker-engine=1.13.1-0~ubuntu-$(lsb_release -cs)"
  # upgrade docker compose as well
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose-new
  - chmod +x docker-compose-new

before_script:
  - ./docker-compose-new build jupyter-notebook
  - TAG=latest ./docker-compose-new build jupyter-notebook
  - ./docker-compose-new build server
  - TAG=latest ./docker-compose-new build server
script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - ./docker-compose-new push
  - TAG=latest ./docker-compose-new push
  - openssl aes-256-cbc -K $encrypted_a3016063d1da_key -iv $encrypted_a3016063d1da_iv -in key.enc -out key -d
  - chmod 600 key
  - "scp -i key  -o StrictHostKeyChecking=no docker-compose.yml $SERVER_USERNAME@$EXTERNAL_DOCKER_HOST"
  - ssh -i key -o StrictHostKeyChecking=no $SERVER_USERNAME@$EXTERNAL_DOCKER_HOST sudo TAG=${TAG} SERVER_HOST=${EXTERNAL_DOCKER_HOST} docker stack deploy -c docker-compose.yml ici-recorder
