version: '3'
services:
  # jupyterhub:
  #   build: jupyterhub
  #   environment:
  #     DOCKER_NOTEBOOK_IMAGE: "saulshanabrook/ici-recorder-jupyter-notebook"
  #     DOCKER_NETWORK_NAME: "icirecorder_default"
  #   volumes:
  #     # Bind Docker socket on the host so we can connect to the daemon from
  #     # within the container
  #     - "/var/run/docker.sock:/var/run/docker.sock:rw"
  #   ports:
  #    - "443:443"
  jupyter-notebook:
    build: jupyter-notebook
    image: icirecorder/jupyter-notebook:${TAG:-latest}
    volumes:
      - ./data/notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.password='sha1:b689bdb78b77:c2e53af00e537fd286497049896c4487d69b6089'
    ports:
      - "80:8888"
  jupyter-notebook-test:
    build: jupyter-notebook
    working_dir: /tmp/test
    command: python -m unittest
    volumes:
      - ./jupyter-notebook/test:/tmp/test
    environment:
      CLOJUSH-PARQUET-URI: "alluxio://alluxio:19998/clojush/"
  alluxio:
    build: alluxio
    image: icirecorder/alluxio:${TAG:-latest}
    volumes:
      # - ./storage:/tmp/storage
      - ./data/underfs:/tmp/underfs
      # - ./journal:/tmp/alluxio-1.4.0/journal/
      # - ./logs:/tmp/alluxio-1.4.0/logs
    ports:
      - "19999:19999"
      - "30000:30000"
      - "19998:19998"
  clojure:
    build: clojure
    volumes:
      - ./clojure:/usr/src/app/
    environment:
      CLOJUSH-PARQUET-URI: "alluxio://alluxio:19998/clojush/"
