version: '3.2'
services:
  test-alluxio:
    build: alluxio-server
    entrypoint: bin/alluxio
    command: runTests
    environment:
      ALLUXIO_MASTER_HOSTNAME: ${SERVER_HOST:-alluxio-master}

  test-jupyter-notebook:
    build: jupyter-notebook
    working_dir: /tmp/test
    command: python -m unittest
    volumes:
      - ./jupyter-notebook/test:/tmp/test
    environment:
      CLOJUSH-PARQUET-URI: "alluxio://alluxio-master:19998/clojush/"
  test-clojure:
    build: clojure
    volumes:
      - ./clojure:/usr/src/app/
    environment:
      CLOJUSH-PARQUET-URI: "alluxio://alluxio-master:19998/clojush/"
  build-alluxio:
    build:
      context: alluxio
      args:
        ALLUXIO_REF: addadd2a4d58814e2aacc785df457fd4d6e35f31
