version: '3.2'
services:
  # jupyterhub:
  #   build: jupyterhub
  #   environment:
  #     DOCKER_NOTEBOOK_IMAGE: "saulshanabrook/ici-recorder-jupyter-notebook"
  #     DOCKER_NETWORK_NAME: "icirecorder_default"
  #   volumes:
  #     # Bind Docker socket on the host so we can connect to the daemon from
  #     # within the container
  #     - "/var/run/docker.sock:/var/run/docker.sock:rw"
  #   ports:
  #    - "443:443"
  # server-configs:
  #   build: server
  #   image: icirecorder/server:${TAG:-latest}
  #   expose:
  #     - 9990
  #   ports:
  #     - "9990:9990"
  #   environment:
  #     PORT: 9990
  #     FOLDER: /output
  #   volumes:
  #     - configs:/output
  server:
    build: server
    image: icirecorder/server:${TAG:-latest}
    expose:
      - 9990
    ports:
      - "9990:9990"
    environment:
      PORT: 9990
      FOLDER: /output
    volumes:
      - input:/output
  jupyter-notebook:
    build: jupyter-notebook
    image: icirecorder/jupyter-notebook:${TAG:-latest}
    volumes:
      - notebooks:/home/jovyan/work
      - jupyter-settings:/home/jovyan/.jupyter/nbconfig
      - input:/input
      - output:/output
    command: start-notebook.sh --NotebookApp.password='sha1:b689bdb78b77:c2e53af00e537fd286497049896c4487d69b6089'
    environment:
      INPUT_FOLDER: /input/final
      OUTPUT_FOLDER: /output/
    expose:
      - 4040
    ports:
      - "8888:8888"
      - "4040:4040"
    deploy:
      resources:
        limits:
          memory: 3G
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
volumes:
  notebooks:
  jupyter-settings:
  input:
  output:
