version: '3.2'
services:
  test-jupyter-notebook:
    build: jupyter-notebook
    working_dir: /tmp/test
    command: python -m unittest
    volumes:
      - ./jupyter-notebook/test:/tmp/test
    environment:
      CLOJUSH-PARQUET-URI: "hdfs://hadoop-namenode:8020/clojush/"
  test-clojure:
    build: clojure
    volumes:
      - ./clojure:/usr/src/app/
    environment:
      CLOJUSH-PARQUET-URI: "hdfs://hadoop-namenode:8020/clojush/"
