---
- hosts: all
  remote_user: root
  gather_facts: no
  vars:
    underfs: /mnt/volume-nyc1-01
  pre_tasks:
     - name: 'install python2'
       raw: sudo apt-get -y install python-simplejson
  tasks:
    - include: tasks/alluxio.yml
